using Application.Core.Common.Enums;
using System.Collections.Generic;

namespace Application.Core.Nutrition.MealComponents.Base
{
    /// <summary>
    /// Base part of the meal component for which is amount being calculated.
    /// </summary>
    internal abstract class WeightLimitedMealComponent : MealComponent
    {
        /// <summary>
        /// The maximum possible amount of meal component.
        /// </summary>
        internal int MaximumAmount { get; init; }

        /// <summary>
        /// Portion of macronutrient amount generated by meal component.
        /// </summary>
        internal double Ratio { get; set; }

        /// <summary>
        /// List of meal component names and ratios of this meal component against them.
        /// </summary>
        internal virtual Dictionary<string, double> SameMacroNutrientRatios { get; } = new Dictionary<string, double>();

        /// <summary>
        /// Initialize a new instance of <see cref="WeightLimitedMealComponent" /> with the given majoritarian
        /// macronutrient and maximum amount in grams.
        /// </summary>
        /// <param name="majoritarian">macronutrient with the largest representation.</param>
        /// <param name="maximumAmount">maximum allowed amount of ingredient in the meal component.</param>
        protected WeightLimitedMealComponent(MacroNutrient majoritarian, int maximumAmount) : base(majoritarian)
        {
            MaximumAmount = maximumAmount;
        }
    }
}